language: ruby
dist: xenial

branches:  # travis build limitations
  only:
    - website  # for /marinebon/ioos_jekyll_theme website content
    - master  # for future clones of the website branch using master
    # - theme  # for /marinebon/ioos_jekyll_theme jeykll theme

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install

script:
    # For jekyll/jekyll#6374
    - git submodule update --remote --recursive
    # build site
    - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:  # deployment limitations
    branch: website

  local_dir: _site
  # fqdn: travis-blogdown.yihui.name  # this sets CNAME for custom DN

notifications:
  email:
    recipients:
    - tylarmurray@mail.usf.edu.com
    on_success: never
    on_failure: change
