language: ruby
dist: xenial

branches:
  only:
    - master

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install

script:
    # For jekyll/jekyll#6374
    - git submodule update --remote --recursive
    # build site
    - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  # fqdn: travis-blogdown.yihui.name  # this sets CNAME for custom DN

notifications:
  email:
    recipients:
    - tylarmurray@mail.usf.edu.com
    on_success: never
    on_failure: change
